package org.example.lesson3;

// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class SignInTest {
    private static WebDriver driver;


    @BeforeAll
    public static void setUp() {
        driver = new ChromeDriver();

    }

    @AfterAll
    public static void tearDown() {
        driver.quit();
    }

    @Test
    public void signIn() {
        driver.get("https://magento.softwaretestingboard.com/");
        driver.findElement(By.xpath("//a[contains(text(),\'Sign In\')]")).click();
        driver.findElement(By.xpath("//*[@id=\"email\"]")).sendKeys("roni_cost@example.com");
        driver.findElement(By.xpath("//input[@id=\'pass\']")).sendKeys("roni_cost3@example.com");
        driver.findElement(By.xpath("//button[@class=\"action login primary\"]")).click();
    }
}
